### ISSUE TITLE
The direction of the 3D data test result is inconsistent with the original data

### ISSUE THREAD

**Issue by Emmally6** [juglab/n2v#122] opened 2022-06-23 14:07 UTC
Hello,I want to know why the direciton of the nii data test result is inconsistent with the original data.

**Comment by tibuch** [comment] 2022-06-27 07:39
Hi,

What do you mean by nii data test result? And what do you mean by direction?

**Comment by Emmally6** [comment] 2022-06-29 02:42
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Thank you for your reply. 
        I used n2v to denoise the MRI nii format data, the direction of the denoised result is inconsistent with the original nii data.It can be seen in the attachment.
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                17376324
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 06/27/2022 15:39，Tim-Oliver ***@***.***> wrote： 



Hi,
What do you mean by nii data test result? And what do you mean by direction?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tibuch** [comment] 2022-06-29 06:58
Please provide more information and consider answering in the github issue. 

N2V is not changing the data orientation. Most likely the input is already in the wrong direction.

**Comment by jdeschamps** [comment] 2023-01-23 09:26
Lack of answer, so I will close this issue since we couldn't reproduce it..

**Closed by jdeschamps** 2023-01-23 09:26 UTC
