### ISSUE TITLE
How to run through the code

### ISSUE THREAD

**Issue by tianshukai99** [juglab/n2v#142] opened 2023-08-10 00:32 UTC
Hello, I have some questions for you.
1. i have 384*288 infrared images now, what should i use to train with my data? Should I use trainN2V.py or which one?
2.Which folder do I put my data in when training, and what is the exact process to run through the code?

**Comment by jdeschamps** [comment] 2023-08-10 08:16
Hi,

1. I would suggest you use one of the jupyter notebook, e.g. [this one](https://github.com/juglab/n2v/blob/main/examples/2D/denoising2D_BSD68/BSD68_reproducibility.ipynb). You will need to adapt the loading data part to your own images. If you are not comfortable with writing python code, then you can use the [napari plugin](https://github.com/juglab/napari-n2v).
2. In the notebooks, the data is loaded in memory so you need to simply point to the right folder and then use a function to load the data. If you have tiff images, then you could use the [tifffile package](https://pypi.org/project/tifffile/) to load the images. Then you run each cell of the notebook one by one and make sure that you adapt them to your data.

If you don't know how to use jupyter notebooks, I suggest this [tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/). Note that it still requires being able to write python code.
If you are not comfortable with programming in python, then you can use the [napari plugin](https://github.com/juglab/napari-n2v). It requires setting up the conda environment properly, the rest is through a user interface.

**Comment by jdeschamps** [comment] 2023-08-29 07:17
I will close this issue due to lack of answer, don't hesitate to comment on it if you want it reopen or to open a new one.

**Closed by jdeschamps** 2023-08-29 07:17 UTC
