### ISSUE TITLE
Updating N2V to N2V2 settings

### ISSUE THREAD

**Issue by bmburkel** [juglab/n2v#144] opened 2023-08-28 20:12 UTC
Hi. I am a breast cancer researcher, and I do a lot intravital timelapse imaging where we just have a low photon budget. There is only so much one can do within the constraints of our model system. That is why I have an interest in your program. Thus far, I have been trying to use your program, N2V, for about a month. Initially, I used it within FIJI. It worked great, except for the fact that it introduced a checkerboard artifact. Upon a little more research, I realized that you already have a solution to this problem, N2V2. Unfortunately, that is not available in the FIJI plugin. So, I looked into Napari. Unfortunately, I had several problems. If I used, the most current Napari, I can open my images, but if I load the version compatible with N2V, it will no longer open the images. Secondly, I could never get the Tensor flow to recognize the GPU. As a result of this, I gave the juypter notebook within google colab a try. With the help of ChatGPT, I was able to take the notebook, modify the path to upload images from my google drive, and denoise them. It seemed to work as I expected. Next, I wanted to change the Config file to incorporate those settings to make N2V into N2V2. I am able to find those parameters in the config file and change them, but they don't seem to update the program. The output retains the same setting of the N2V. I am not coder, and I do not know python. It seems like this should be a doable thing, but maybe it is way more complicated than my rudimentary understanding allows for. I am motivated to fix this and use your program. Can you describe some steps I could to take to modify the N2VConfig and have it recognized by your program? Any insight would be greatly appreciated.

**Comment by jdeschamps** [comment] 2023-08-29 07:16
Hi,

I am sorry you encountered difficulties! 

👎 The Fiji plugin is unfortunately not maintained anymore, because the libraries it relies on are out-dated. We are waiting for new development in the field that would allow more modern code to run, but it will take quite an engineering effort. We are currently focusing on napari.

👎 The Colab notebooks are maintained by other people, and it might very well be that it was not updated when N2V2 was published. Therefore it probably uses an old version. We are working on a new library that will incorporate N2V2 and other algorithms, we will make a Colab notebook probably, but this will be next year.

👍 I invite you to post your problem about the napari-n2v plugin here: https://github.com/juglab/napari-n2v/issues. Let's try to make it work! In the mean time, I will test the plugin with more recent versions of napari and make it compatible.

In the new issue (on napari-n2v repository), could specify the following:
- type of images (maybe a small link to similar images so I can reproduce the problem)
- the TF, cuda and cudnn versions that you installed
- the GPU that you have

**Comment by jdeschamps** [comment] 2023-08-29 13:33
Regarding recent napari versions, this should be fix in the latest version: https://github.com/juglab/napari-n2v/releases/tag/v0.1.1

**Comment by bmburkel** [comment] 2023-08-30 03:18
Hi, Joran. I really appreciate your help. I reinstalled Napari with your zip file and now it seems to be working. The images can be loaded, and the algorithm seems to working. The GUI and interface are a nice touch too. Unfortunately, I still can’t the GPU to be recognized. Maybe it is a path thing or something. I don’t know. It seems like it should work. It is a windows 10 system and I am running Tensorflow 2.10.1. The GPU is a GeForce GTX 1650 with  CUDA 11.2 and CuDNN 8.1. When I query the computer through the prompt, it identifies the GPU. I can generate a tensor with the CPU. I just cant get it to use the GPU to create the tensor. Once again, thanks for your help!

Brian

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jdeschamps** [comment] 2023-08-30 08:13
Hi,

The release is actually available through pip, not need to use the zip.

Can you open an issue in the correct repository: https://github.com/juglab/napari-n2v/issues

Then I'll try to help from there. Thanks!

I will close this issue now since Colab and Fiji plugins are not N2V2 compatible.

**Closed by jdeschamps** 2023-08-30 08:13 UTC
